const LANGUAGE_KEY = 'etler-hub-language';

const translations = {
  en: {
    'language.switch': '中文',
    'language.switchToEnglish': 'Switch to English',
    'language.switchToChinese': 'Switch to Chinese',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.switchToLight': 'Switch to light mode',
    'theme.switchToDark': 'Switch to dark mode',
    'brand.home': 'Etler Hub home',
    'nav.main': 'Main navigation',
    'nav.home': 'Home',
    'nav.free': 'Free Script',
    'nav.config': 'Config Builder',
    'status.online': 'ONLINE',
    'back.hub': '← Back to Hub',
    'status.config': 'CONFIG BUILDER',
    'guide.quick': 'Quick guide',
    'home.eyebrow': 'ETler hub / START HERE',
    'home.title': 'Etler Hub',
    'home.titleAccent': '- A Universal Time Script',
    'home.lede': 'A clean home for your loadouts, tools, and the next generation of Etler utilities.',
    'home.explore': 'Explore the hub',
    'home.orbit.loadouts': 'LOADOUTS',
    'home.orbit.tools': 'TOOLS',
    'home.orbit.etler': 'ETLER',
    'home.sectionEyebrow': 'ETLER HUB',
    'home.sectionTitle': 'Etler Hub modules.',
    'home.module.freeStatus': 'READY',
    'home.module.freeTitle': 'Free Script',
    'home.module.freeCopy': 'Copy the free loadstring and get your key from the Etler Hub Discord server.',
    'home.module.freeLink': 'Open free script',
    'home.module.configStatus': 'CONFIG',
    'home.module.configTitle': 'Kaitun Config',
    'home.module.configCopy': 'Configure and run it in your executor. A paid script is required.',
    'home.module.configLink': 'Open Kaitun config',
    'home.module.communityStatus': 'COMMUNITY',
    'home.module.communityCopy': 'Get your key, meet the community, and keep up with Etler Hub.',
    'home.module.online': 'online',
    'home.module.members': 'members',
    'home.module.join': 'Join server',
    'home.rail.status': 'SYSTEM ONLINE',
    'home.rail.build': 'ETLER HUB • FOUNDATION BUILD',
    'free.eyebrow': 'ETLER HUB / FREE ACCESS',
    'free.title': 'Free',
    'free.titleAccent': 'Script.',
    'free.copy': 'Copy the loadstring below, then grab your key from the Etler Hub Discord server.',
    'free.loadstring': 'LOADSTRING',
    'free.ready': 'READY TO COPY',
    'free.copied': 'COPIED',
    'free.copyButton': 'Copy',
    'free.keys': 'Keys needed. Get one in the Discord server below.',
    'discord.joinAria': 'Join the Etler Hub Discord server',
    'discord.online': 'online',
    'discord.members': 'members',
    'discord.join': 'Join',
    'free.back': '← Back to Etler Hub',
    'free.openConfig': 'Open config builder →',
    'toast.loadstringCopied': 'Loadstring copied to clipboard',
    'toast.selectLoadstring': 'Select and copy the loadstring',
    'config.warningOne': "BEFORE USING KAITUN CONFIG, MAKE SURE YOU HAVE BOUGHT A PAID SCRIPT, OR ELSE YOU WON'T BE ABLE TO USE IT",
    'config.warningTwo': "YOU CAN BUY THE PAID SCRIPT IN ETLER HUB'S DISCORD SERVER",
    'config.eyebrow': 'BOUNDLESS TOWER LOADOUT',
    'config.title': 'Build your farm.',
    'config.titleAccent': 'Leave the rest to Etler.',
    'config.copy': 'Tune your traits, paste your key, and generate a ready-to-run config in seconds.',
    'config.badgeTitle': 'Overnight ready',
    'config.badgeCopy': 'Auto-saves your choices locally',
    'config.builderAria': 'Configuration builder',
    'config.connectTitle': 'Connect your loader',
    'config.connectCopy': 'These two values are used only in the generated script.',
    'config.scriptKey': 'Script key',
    'required': 'required',
    'config.scriptKeyPlaceholder': 'Paste your script key',
    'config.showKey': 'Show',
    'config.hideKey': 'Hide',
    'config.loaderFile': 'Loader file',
    'config.fixedLoaderAria': 'Fixed loader file',
    'locked': 'LOCKED',
    'config.note': 'Keep your config above the loadstring line. Never share your script key.',
    'config.choicesTitle': 'Choices',
    'config.choicesCopy': 'Pick the traits to farm for each stand group. Groups run from top to bottom.',
    'config.addGroup': 'Add priority group',
    'config.behaviorTitle': 'Set farm behavior',
    'config.behaviorCopy': 'Everything starts with safe, overnight-friendly defaults.',
    'config.farmRules': 'Farm rules',
    'core': 'CORE',
    'config.floorCap': 'Floor cap',
    'floors': 'floors',
    'config.webhook': 'Webhook',
    'optional': 'optional',
    'config.itemsKeep': 'Items to keep',
    'config.commaSeparated': 'optional · comma separated',
    'config.itemsPlaceholder': "UCoins, Saint's Corpse",
    'config.autoChest': 'Auto chest',
    'config.autoChestCopy': 'Open chests as you farm',
    'config.autoAscend': 'Auto ascend',
    'config.autoAscendCopy': 'Spend UCoins to reset your level',
    'config.optimization': 'Optimization',
    'performance': 'PERFORMANCE',
    'config.fpsCap': 'FPS cap',
    'fps': 'fps',
    'config.ecoMode': 'Eco mode',
    'config.ecoModeCopy': 'Minimum graphics',
    'config.stopRendering': 'Stop rendering',
    'config.stopRenderingCopy': 'Lowest GPU usage',
    'config.debugMode': 'Debug mode',
    'config.debugModeCopy': 'Show extra logs',
    'config.combatAssist': 'Combat assist',
    'config.summonStand': 'Summon stand',
    'config.summonStandCopy': 'Keep your stand active',
    'config.buso': 'Buso Haki',
    'config.busoCopy': 'Keep Haki active',
    'config.autoSkills': 'Auto skills',
    'config.autoSkillsCopy': 'Cast abilities automatically',
    'config.skillKeys': 'Skill keys',
    'config.skillKeysCopy': 'leave blank to fire all',
    'config.skinTitle': 'Skin settings',
    'config.skinCopy': 'Optional recycling and forging while you farm.',
    'config.keepRarities': 'Keep rarities',
    'rarity.rare': 'Rare',
    'rarity.epic': 'Epic',
    'rarity.legendary': 'Legendary',
    'rarity.event': 'Event',
    'rarity.mythic': 'Mythic',
    'rarity.universal': 'Universal',
    'config.recycle': 'Recycle skins',
    'config.keepPremium': 'Keep premium',
    'config.keepUnusuals': 'Keep unusuals',
    'config.forgeUnusuals': 'Forge unusuals',
    'config.buyCrates': 'Buy crates',
    'config.generated': 'GENERATED CONFIG',
    'config.unsaved': 'UNSAVED',
    'config.ready': 'READY',
    'config.copyCode': 'Copy code',
    'config.generatedAria': 'Generated Lua config',
    'config.updatesLive': 'Updates live',
    'config.download': 'Download .lua',
    'config.bestPractice': 'BEST PRACTICE',
    'config.saveAuto': 'Save it to auto-execute',
    'config.saveAutoCopy': 'The farm teleports between the lobby and tower. Auto-execute re-runs your config after each teleport.',
    'config.traitNaming': 'Trait naming',
    'config.patterns': '5 patterns',
    'config.exactTrait': 'Exact trait',
    'config.hexedVersion': 'Hexed version',
    'config.anyPlainMythic': 'Any plain Mythic',
    'config.anyHexedMythic': 'Any hexed Mythic',
    'config.anyHexedTrait': 'Any hexed trait',
    'config.traitNote': 'Plain and hexed pools are separate. List both if either one works for you.',
    'config.footerBuilder': 'ETLER HUB • LOADOUT BUILDER',
    'config.footerDefault': 'Everything else stays at a sensible default.',
    'guide.eyebrow': 'ETLER HUB / QUICK GUIDE',
    'guide.title': 'Etler Hub — Trait Farm Setup',
    'guide.close': 'Close quick guide',
    'guide.lead': "Farm traits while you're away. Three steps.",
    'guide.stepOne': 'Paste your key into',
    'guide.stepTwo': 'Change',
    'guide.stepThree': "Save it into your executor's auto-execute folder, then join the game.",
    'guide.defaults': 'Everything else already has sensible defaults — leave it alone unless you want to change something.',
    'guide.naming': 'Naming your traits',
    'guide.stopsFirst': 'It stops on the first one that lands.',
    'guide.exact': 'that exact trait',
    'guide.hexedIt': 'the hexed version of it',
    'guide.anyMythicPlain': 'any Mythic trait, plain only',
    'guide.anyHexedMythic': 'any hexed Mythic',
    'guide.anyHexedAtAll': 'any hexed trait at all',
    'guide.separatePools': ' does not include hexed Mythics. List both, as above, if you want either.',
    'guide.completeExample': 'Complete example',
    'guide.towerCopy': 'It takes you to Boundless Tower, farms, and rolls traits until one you asked for lands.',
    'guide.breaks': 'Three things that break it',
    'guide.breakAuto': 'Use the auto-execute folder. The farm teleports between the lobby and the tower, and only auto-execute re-runs the script after a teleport. Run it by hand and it stops at the first one.',
    'guide.breakConfig': 'Keep the config above the loadstring line. Below it, and it\'s ignored.',
    'guide.breakWindow': 'No window is normal. With a config, the hub runs hidden. Delete the whole Config block if you want the clickable hub back.',
    'guide.lookBroken': "Two things that look broken but aren't",
    'guide.skippedStand': 'It skipped my stand. Every copy already has a trait you asked for. Rolling it would destroy the good trait you already have.',
    'guide.typo': 'It stopped and named a typo. A name that matches nothing halts the script and tells you what you probably meant — better than guessing and rolling the wrong stand.',
    'guide.picking': 'Picking what to farm',
    'guide.lineCopy': 'Each line is one group, farmed top to bottom. Several stands on one line share the same target traits.',
    'guide.fiveWays': 'Five ways to name a trait',
    'guide.anyHexed': 'any hexed trait',
    'guide.allMythic': 'any plain Mythic; also All Legendary and All Epic',
    'guide.allMythicHexed': 'any hexed Mythic; also All Legendary Hexed',
    'guide.separate': ' and ',
    'guide.separateCopy': ' are separate — the plain form never accepts a hexed roll. List both if you\'ll take either.',
    'guide.case': 'Capitals, spaces, and punctuation don\'t matter —',
    'guide.prime': ' and a hexed Prime is kept too — it\'s strictly better, so it\'s never rolled away.',
    'guide.ucoins': 'Just want UCoins, not traits?',
    'guide.ucoinsLead': 'Leave',
    'guide.ucoinsCopy': 'Empty traits means it never touches the roller — so it farms on your spec, normally skipped for being too good, and can\'t roll over a trait you wanted to keep.',
    'guide.otherSettings': 'The other settings',
    'guide.floor': 'clear this floor, then restart, 0 climbs forever.',
    'guide.items': 'auto-sell clears everything else to stop your bag filling up. Anything named here is never sold and is stored automatically the moment it drops. A floor won\'t skip until it\'s safely stored.',
    'guide.optimization': ' caps your framerate,',
    'guide.optimizationEnd': ' drops graphics to the minimum. Both are worth it for an overnight farm.',
    'guide.ascend': ' set false to keep your UCoins. Ascending spends them and resets your level.',
    'guide.combat': ' keeps Haki up,',
    'guide.combatEnd': ' casts your abilities.',
    'guide.webhook': ' Discord ping each time a trait is secured. Your username is spoilered.',
    'guide.skins': ' recycles skins into points, forges points into unusuals, while you farm.',
    'guide.step1Html': 'Paste your key into <code>script_key</code> and change the loader.', 'guide.step2Html': 'Change <code>"Standless"</code> to the stand you want, and <code>Wanted_Traits</code> to the traits you want.', 'guide.step3Html': "Save it into your executor's auto-execute folder, then join the game.", 'guide.separateHtml': '<code>"All Mythic"</code> does not include hexed Mythics. List both, as above, if you want either.', 'guide.caseHtml': 'Capitals, spaces, and punctuation don\'t matter — <code>"the vessel"</code> works.', 'guide.primeHtml': 'Ask for <code>"Prime"</code> and a hexed Prime is kept too — it\'s strictly better, so it\'s never rolled away.', 'guide.ucoinsLeadHtml': 'Leave <code>Wanted_Traits</code> empty and turn ascending off:', 'guide.ucoinsCopyHtml': 'Empty traits means it never touches the roller — so it farms on your spec, normally skipped for being too good, and can\'t roll over a trait you wanted to keep. <code>Auto_Ascend = false</code> keeps the coins instead of spending them.', 'guide.floorHtml': '<strong>Floor_Cap</strong> — clear this floor, then restart, 0 climbs forever.', 'guide.itemsHtml': '<strong>ItemsToKeep</strong> — auto-sell clears everything else to stop your bag filling up. Anything named here is never sold and is stored automatically the moment it drops. A floor won\'t skip until it\'s safely stored.', 'guide.optimizationHtml': '<strong>Optimization</strong> — <code>Fps_Cap</code> caps your framerate, <code>Eco_Mode</code> drops graphics to the minimum. Both are worth it for an overnight farm.', 'guide.ascendHtml': '<strong>Farming.Auto_Ascend</strong> — set false to keep your UCoins. Ascending spends them and resets your level.', 'guide.combatHtml': '<strong>Combat</strong> — <code>Auto_Buso_Haki</code> keeps Haki up, <code>Auto_Skills</code> casts your abilities. <code>Skill_Keys = {}</code> fires every key; name them like <code>{ "R", "T" }</code> to pick. Charged keys use +, like <code>"R+"</code>.', 'guide.webhookHtml': '<strong>WebHook</strong> — Discord ping each time a trait is secured. Your username is spoilered.', 'guide.skinsHtml': '<strong>Skins_Settings</strong> — recycles skins into points, forges points into unusuals, while you farm. <code>Keep_Rarities</code> is what you protect — everything else is melted. Valid: Rare, Epic, Legendary, Event, Mythic, Universal. Limited, Unobtainable, equipped, and locked skins are never touched.', 'guide.breakAutoHtml': '<strong>Use the auto-execute folder.</strong> The farm teleports between the lobby and the tower, and only auto-execute re-runs the script after a teleport. Run it by hand and it stops at the first one.', 'guide.breakConfigHtml': '<strong>Keep the config above the loadstring line.</strong> Below it, and it\'s ignored.', 'guide.breakWindowHtml': '<strong>No window is normal.</strong> With a config, the hub runs hidden. Delete the whole Config block if you want the clickable hub back.', 'guide.skippedStandHtml': '<strong>It skipped my stand.</strong> Every copy already has a trait you asked for. Rolling it would destroy the good trait you already have.', 'guide.typoHtml': '<strong>It stopped and named a typo.</strong> A name that matches nothing halts the script and tells you what you probably meant — better than guessing and rolling the wrong stand.', 'guide.separatePoolsHtml': '<code>"All Mythic"</code> and <code>"All Mythic Hexed"</code> are separate — the plain form never accepts a hexed roll. List both if you\'ll take either.',
    'toast.configCopied': 'Config copied to clipboard',
    'toast.selectConfig': 'Select and copy the config',
    'toast.downloaded': 'Downloaded etler-config.lua',
    'trait.select': 'Select traits',
    'trait.choices': 'Trait choices',
    'trait.heading': 'SELECT TRAITS',
    'trait.standsPlaceholder': 'Standless, The Vessel',
    'trait.remove': 'Remove group {n}',
  },
  zh: {
    'language.switch': 'English',
    'language.switchToEnglish': '切换到英文',
    'language.switchToChinese': '切换到中文',
    'theme.light': '浅色',
    'theme.dark': '深色',
    'theme.switchToLight': '切换到浅色模式',
    'theme.switchToDark': '切换到深色模式',
    'brand.home': 'Etler Hub 首页',
    'nav.main': '主导航', 'nav.home': '首页', 'nav.free': '免费脚本', 'nav.config': '配置生成器',
    'status.online': '在线', 'back.hub': '← 返回 Hub', 'status.config': '配置生成器', 'guide.quick': '快速指南',
    'home.eyebrow': 'ETler hub / 从这里开始', 'home.title': 'Etler Hub', 'home.titleAccent': '- 通用时间脚本',
    'home.lede': '为你的配置、工具和新一代 Etler 实用程序打造的整洁中心。', 'home.explore': '探索 Hub',
    'home.orbit.loadouts': '配置', 'home.orbit.tools': '工具', 'home.orbit.etler': 'ETLER', 'home.sectionEyebrow': 'ETLER HUB', 'home.sectionTitle': 'Etler Hub 模块。',
    'home.module.freeStatus': '就绪', 'home.module.freeTitle': '免费脚本', 'home.module.freeCopy': '复制免费的加载代码，并从 Etler Hub Discord 服务器获取密钥。', 'home.module.freeLink': '打开免费脚本',
    'home.module.configStatus': '配置', 'home.module.configTitle': 'Kaitun 配置', 'home.module.configCopy': '配置并在执行器中运行。需要付费脚本。', 'home.module.configLink': '打开 Kaitun 配置',
    'home.module.communityStatus': '社区', 'home.module.communityCopy': '获取密钥、认识社区成员，并关注 Etler Hub 的最新动态。', 'home.module.online': '在线', 'home.module.members': '成员', 'home.module.join': '加入服务器',
    'home.rail.status': '系统在线', 'home.rail.build': 'ETLER HUB • 基础版本',
    'free.eyebrow': 'ETLER HUB / 免费访问', 'free.title': '免费', 'free.titleAccent': '脚本。', 'free.copy': '复制下面的加载代码，然后从 Etler Hub Discord 服务器获取密钥。', 'free.loadstring': '加载代码', 'free.ready': '准备复制', 'free.copied': '已复制', 'free.copyButton': '复制', 'free.keys': '需要密钥。请在下方 Discord 服务器获取。',
    'discord.joinAria': '加入 Etler Hub Discord 服务器', 'discord.online': '在线', 'discord.members': '成员', 'discord.join': '加入', 'free.back': '← 返回 Etler Hub', 'free.openConfig': '打开配置生成器 →',
    'toast.loadstringCopied': '加载代码已复制到剪贴板', 'toast.selectLoadstring': '请选择并复制加载代码',
    'config.warningOne': '使用 KAITUN 配置前，请确认你已购买付费脚本，否则无法使用。', 'config.warningTwo': '你可以在 ETLER HUB 的 Discord 服务器购买付费脚本。', 'config.eyebrow': 'BOUNDLESS TOWER 配置', 'config.title': '打造你的农场。', 'config.titleAccent': '剩下的交给 Etler。', 'config.copy': '调整词条、粘贴密钥，几秒内生成可直接运行的配置。', 'config.badgeTitle': '适合挂机', 'config.badgeCopy': '你的选择会自动保存在本地', 'config.builderAria': '配置生成器',
    'config.connectTitle': '连接加载器', 'config.connectCopy': '这两个值只会用于生成的脚本。', 'config.scriptKey': '脚本密钥', 'required': '必填', 'config.scriptKeyPlaceholder': '粘贴你的脚本密钥', 'config.showKey': '显示', 'config.hideKey': '隐藏', 'config.loaderFile': '加载器文件', 'config.fixedLoaderAria': '固定的加载器文件', 'locked': '已锁定', 'config.note': '请将配置放在加载代码上方。不要分享你的脚本密钥。',
    'config.choicesTitle': '选择', 'config.choicesCopy': '为每组 Stand 选择要刷的词条。分组会从上到下依次执行。', 'config.addGroup': '添加优先级分组', 'config.behaviorTitle': '设置刷取行为', 'config.behaviorCopy': '所有设置默认采用安全、适合挂机的选项。', 'config.farmRules': '刷取规则', 'core': '核心', 'config.floorCap': '楼层上限', 'floors': '层', 'config.webhook': 'Webhook', 'optional': '可选', 'config.itemsKeep': '保留物品', 'config.commaSeparated': '可选 · 用逗号分隔', 'config.itemsPlaceholder': 'UCoins, Saint\'s Corpse', 'config.autoChest': '自动开箱', 'config.autoChestCopy': '刷取时打开宝箱', 'config.autoAscend': '自动升阶', 'config.autoAscendCopy': '使用 UCoins 重置等级',
    'config.optimization': '优化', 'performance': '性能', 'config.fpsCap': 'FPS 上限', 'fps': 'fps', 'config.ecoMode': '省电模式', 'config.ecoModeCopy': '最低画质', 'config.stopRendering': '停止渲染', 'config.stopRenderingCopy': '最低 GPU 占用', 'config.debugMode': '调试模式', 'config.debugModeCopy': '显示额外日志', 'config.combatAssist': '战斗辅助', 'config.summonStand': '召唤 Stand', 'config.summonStandCopy': '保持 Stand 激活', 'config.buso': '武装色霸气', 'config.busoCopy': '保持霸气激活', 'config.autoSkills': '自动技能', 'config.autoSkillsCopy': '自动释放技能', 'config.skillKeys': '技能按键', 'config.skillKeysCopy': '留空则释放全部',
    'config.skinTitle': '皮肤设置', 'config.skinCopy': '刷取时可选的回收与锻造设置。', 'config.keepRarities': '保留稀有度', 'rarity.rare': '稀有', 'rarity.epic': '史诗', 'rarity.legendary': '传说', 'rarity.event': '活动', 'rarity.mythic': '神话', 'rarity.universal': '通用', 'config.recycle': '回收皮肤', 'config.keepPremium': '保留高级皮肤', 'config.keepUnusuals': '保留特殊皮肤', 'config.forgeUnusuals': '锻造特殊皮肤', 'config.buyCrates': '购买箱子',
    'config.generated': '生成的配置', 'config.unsaved': '未保存', 'config.ready': '就绪', 'config.copyCode': '复制代码', 'config.generatedAria': '生成的 Lua 配置', 'config.updatesLive': '实时更新', 'config.download': '下载 .lua', 'config.bestPractice': '最佳实践', 'config.saveAuto': '保存到自动执行目录', 'config.saveAutoCopy': '农场会在大厅和高塔之间传送。自动执行会在每次传送后重新运行配置。', 'config.traitNaming': '词条命名', 'config.patterns': '5 种模式', 'config.exactTrait': '精确词条', 'config.hexedVersion': 'Hexed 版本', 'config.anyPlainMythic': '任意普通 Mythic', 'config.anyHexedMythic': '任意 Hexed Mythic', 'config.anyHexedTrait': '任意 Hexed 词条', 'config.traitNote': '普通与 Hexed 词条池彼此独立。如果两者都可以接受，请把它们都列出来。', 'config.footerBuilder': 'ETLER HUB • 配置生成器', 'config.footerDefault': '其他设置保持合理默认值。',
    'guide.eyebrow': 'ETLER HUB / 快速指南', 'guide.title': 'Etler Hub — 词条刷取设置', 'guide.close': '关闭快速指南', 'guide.lead': '离开时也能刷词条。只需三步。', 'guide.stepOne': '将密钥粘贴到', 'guide.stepTwo': '将', 'guide.stepThree': '保存到执行器的自动执行文件夹，然后进入游戏。', 'guide.defaults': '其他设置已经是合理默认值——除非你想调整，否则无需修改。', 'guide.naming': '词条命名', 'guide.stopsFirst': '命中第一个符合条件的词条后停止。', 'guide.exact': '该精确词条', 'guide.hexedIt': '它的 Hexed 版本', 'guide.anyMythicPlain': '任意普通 Mythic 词条', 'guide.anyHexedMythic': '任意 Hexed Mythic', 'guide.anyHexedAtAll': '任意 Hexed 词条', 'guide.separatePools': ' 不包含 Hexed Mythic。如果两者都想要，请像上面一样都列出。', 'guide.completeExample': '完整示例', 'guide.towerCopy': '它会带你前往 Boundless Tower，刷取并不断重roll，直到出现你指定的词条。', 'guide.breaks': '三个常见问题', 'guide.breakAuto': '使用自动执行文件夹。农场会在大厅和高塔之间传送，只有自动执行会在传送后重新运行脚本。手动运行会在第一次传送后停止。', 'guide.breakConfig': '请将配置放在加载代码上方。放在下面会被忽略。', 'guide.breakWindow': '没有窗口是正常的。使用配置后，Hub 会在后台运行。删除整个 Config 区块即可恢复可点击的 Hub。', 'guide.lookBroken': '两个看起来像故障、其实不是的问题', 'guide.skippedStand': '它跳过了我的 Stand。每个复制品已经拥有你要求的词条。重roll 会破坏已有的好词条。', 'guide.typo': '它停止并指出了拼写错误。匹配不到任何内容的名称会让脚本停止，并告诉你可能想输入什么——这比猜测并重roll 错误的 Stand 更安全。', 'guide.picking': '选择要刷的内容', 'guide.lineCopy': '每一行是一个分组，按从上到下的顺序刷取。同一行的多个 Stand 共用目标词条。', 'guide.fiveWays': '五种词条命名方式', 'guide.anyHexed': '任意 Hexed 词条', 'guide.allMythic': '任意普通 Mythic；也包括 All Legendary 和 All Epic', 'guide.allMythicHexed': '任意 Hexed Mythic；也包括 All Legendary Hexed', 'guide.separate': ' 和 ', 'guide.separateCopy': ' 是分开的——普通形式永远不会接受 Hexed 结果。如果两者都接受，请都列出来。', 'guide.case': '大小写、空格和标点不影响——', 'guide.prime': '，Hexed Prime 也会被保留——它更好，所以不会被重roll掉。', 'guide.ucoins': '只想要 UCoins，不想要词条？', 'guide.ucoinsLead': '将', 'guide.ucoinsCopy': '空词条意味着不会触碰重roll器——它会按你的配置刷取通常因太好而被跳过的 Stand，也不会覆盖你想保留的词条。', 'guide.otherSettings': '其他设置', 'guide.floor': '清完该层后重启，设为 0 则无限攀爬。', 'guide.items': '自动出售其他物品，避免背包装满。这里列出的物品永远不会出售，掉落后会立即自动存储。只有安全存储后才会跳过楼层。', 'guide.optimization': ' 限制帧率，', 'guide.optimizationEnd': ' 将画质降到最低。挂机时建议开启。', 'guide.ascend': ' 设为 false 以保留 UCoins。升阶会消耗 UCoins 并重置等级。', 'guide.combat': ' 保持霸气，', 'guide.combatEnd': ' 释放技能。', 'guide.webhook': ' 每次锁定词条时发送 Discord 提醒。你的用户名会被隐藏。', 'guide.skins': ' 将皮肤回收成点数，再将点数锻造成特殊皮肤。',
    'guide.step1Html': '将密钥粘贴到 <code>script_key</code>，并修改加载器。', 'guide.step2Html': '将 <code>"Standless"</code> 改成你想要的 Stand，将 <code>Wanted_Traits</code> 改成你想要的词条。', 'guide.step3Html': '保存到执行器的自动执行文件夹，然后进入游戏。', 'guide.separateHtml': '<code>"All Mythic"</code> 不包含 Hexed Mythic。如果两者都想要，请像上面一样都列出。', 'guide.caseHtml': '大小写、空格和标点不影响——<code>"the vessel"</code> 也可以。', 'guide.primeHtml': '请求 <code>"Prime"</code> 时，Hexed Prime 也会被保留——它更好，所以不会被重roll掉。', 'guide.ucoinsLeadHtml': '将 <code>Wanted_Traits</code> 留空，并关闭自动升阶：', 'guide.ucoinsCopyHtml': '空词条意味着不会触碰重roll器——它会按你的配置刷取通常因太好而被跳过的 Stand，也不会覆盖你想保留的词条。<code>Auto_Ascend = false</code> 会保留 UCoins，而不是消耗它们。', 'guide.floorHtml': '<strong>Floor_Cap</strong> — 清完该层后重启，设为 0 则无限攀爬。', 'guide.itemsHtml': '<strong>ItemsToKeep</strong> — 自动出售其他物品，避免背包装满。这里列出的物品永远不会出售，掉落后会立即自动存储。只有安全存储后才会跳过楼层。', 'guide.optimizationHtml': '<strong>Optimization</strong> — <code>Fps_Cap</code> 限制帧率，<code>Eco_Mode</code> 将画质降到最低。挂机时建议开启。', 'guide.ascendHtml': '<strong>Farming.Auto_Ascend</strong> — 设为 false 以保留 UCoins。升阶会消耗 UCoins 并重置等级。', 'guide.combatHtml': '<strong>Combat</strong> — <code>Auto_Buso_Haki</code> 保持霸气，<code>Auto_Skills</code> 释放技能。<code>Skill_Keys = {}</code> 会释放全部按键；也可以写成 <code>{ "R", "T" }</code> 指定按键。蓄力按键使用 +，例如 <code>"R+"</code>。', 'guide.webhookHtml': '<strong>WebHook</strong> — 每次锁定词条时发送 Discord 提醒。你的用户名会被隐藏。', 'guide.skinsHtml': '<strong>Skins_Settings</strong> — 刷取时将皮肤回收成点数，再将点数锻造成特殊皮肤。<code>Keep_Rarities</code> 是要保护的稀有度，其余都会被熔炼。有效值：Rare、Epic、Legendary、Event、Mythic、Universal。Limited、Unobtainable、已装备和已锁定的皮肤永远不会被处理。', 'guide.breakAutoHtml': '<strong>使用自动执行文件夹。</strong>农场会在大厅和高塔之间传送，只有自动执行会在传送后重新运行脚本。手动运行会在第一次传送后停止。', 'guide.breakConfigHtml': '<strong>请将配置放在加载代码上方。</strong>放在下面会被忽略。', 'guide.breakWindowHtml': '<strong>没有窗口是正常的。</strong>使用配置后，Hub 会在后台运行。删除整个 Config 区块即可恢复可点击的 Hub。', 'guide.skippedStandHtml': '<strong>它跳过了我的 Stand。</strong>每个复制品已经拥有你要求的词条。重roll 会破坏已有的好词条。', 'guide.typoHtml': '<strong>它停止并指出了拼写错误。</strong>匹配不到任何内容的名称会让脚本停止，并告诉你可能想输入什么——这比猜测并重roll 错误的 Stand 更安全。', 'guide.separatePoolsHtml': '<code>"All Mythic"</code> 和 <code>"All Mythic Hexed"</code> 是分开的——普通形式永远不会接受 Hexed 结果。如果两者都接受，请都列出来。',
    'toast.configCopied': '配置已复制到剪贴板', 'toast.selectConfig': '请选择并复制配置', 'toast.downloaded': '已下载 etler-config.lua', 'trait.select': '选择词条', 'trait.choices': '词条选择', 'trait.heading': '选择词条', 'trait.standsPlaceholder': 'Standless, The Vessel', 'trait.remove': '移除第 {n} 组',
  },
};

let language = 'en';

function translate(key, variables = {}) {
  const value = translations[language][key] ?? translations.en[key] ?? key;
  return Object.entries(variables).reduce((result, [name, replacement]) => result.replaceAll(`{${name}}`, replacement), value);
}

function applyLanguage(nextLanguage = language) {
  language = nextLanguage === 'zh' ? 'zh' : 'en';
  document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en';
  document.querySelectorAll('[data-i18n]').forEach((element) => {
    if (element.dataset.i18nHtml === 'true') element.innerHTML = translate(element.dataset.i18n);
    else element.textContent = translate(element.dataset.i18n);
  });
  document.querySelectorAll('[data-i18n-attr]').forEach((element) => {
    element.dataset.i18nAttr.split(';').forEach((pair) => {
      const [attribute, key] = pair.split(':');
      if (attribute && key) element.setAttribute(attribute, translate(key));
    });
  });
  const button = document.getElementById('language-toggle');
  if (button) {
    button.querySelector('#language-label').textContent = translate('language.switch');
    button.setAttribute('aria-label', translate(language === 'zh' ? 'language.switchToEnglish' : 'language.switchToChinese'));
    button.setAttribute('title', translate(language === 'zh' ? 'language.switchToEnglish' : 'language.switchToChinese'));
  }
  window.dispatchEvent(new CustomEvent('languagechange', { detail: { language } }));
}

function initLanguage() {
  try { language = localStorage.getItem(LANGUAGE_KEY) === 'zh' ? 'zh' : 'en'; } catch { language = 'en'; }
  applyLanguage(language);
  document.getElementById('language-toggle')?.addEventListener('click', () => {
    const next = language === 'zh' ? 'en' : 'zh';
    try { localStorage.setItem(LANGUAGE_KEY, next); } catch {}
    applyLanguage(next);
  });
}

window.i18n = { t: translate, applyLanguage, getLanguage: () => language };
initLanguage();
